[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[edge_functions]]
  function = "index"
  path = "/*"

[context.production.environment]
  WORKER_ENV = "production"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  WORKER_ENV = "staging"
  NODE_ENV = "development"

[context.branch-deploy.environment]
  WORKER_ENV = "development"
  NODE_ENV = "development"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self' data:; object-src 'none'; media-src 'self'; frame-src 'none';"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/edge-functions/index"
  status = 200

# Catch-all for SPA routing
[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/index"
  status = 200

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API response headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-API-Key"
    Cache-Control = "no-cache, no-store, must-revalidate"
